### ISSUE TITLE
Is this abandoned? Because it's not working with the latest libs...

### ISSUE THREAD

**Issue by wc-matteo** [morishitter/postcss-important#2]
```
\node_modules\css-annotation\node_modules\postcss\lib\input.js:29
        this.css = css.toString();
                      ^

TypeError: Cannot read property 'toString' of undefined
    at new Input (\node_modules\css-annotation\node_modules\postcss\lib\input.js:29:23)
    at Function.parse (\node_modules\css-annotation\node_modules\postcss\lib\parse.js:17:17)
    at parse (\node_modules\css-annotation\index.js:5:24)
    at plugin (\node_modules\postcss-important\index.js:6:23)
    at Object.<anonymous> (\gulpfile.js:238:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by kono-paku** [comment]
I used this one.
https://github.com/psren/postcss-important-startstop

**Comment by nicothin** [comment]
```
TypeError: Cannot read property 'toString' of undefined
    at new Input (/mnt/d/projects/help/node_modules/css-annotation/node_modules/postcss/lib/input.js:29:24)
    at Function.parse (/mnt/d/projects/help/node_modules/css-annotation/node_modules/postcss/lib/parse.js:17:17)
    at parse (/mnt/d/projects/help/node_modules/css-annotation/index.js:5:24)
    at plugin (/mnt/d/projects/help/node_modules/postcss-important/index.js:6:23)
    at Object.<anonymous> (/mnt/d/projects/help/gulpfile.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

4 years ))
